name: Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "formatted=$(date +'%Y-%m-%dT%H.%M.%S)" >> $GITHUB_OUTPUT
        shell: bash
        id: timestamp
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          NAME: v${{ steps.timestamp.outputs.formatted }}-${{ github.sha }}
        with:
          tag: ${{ env.NAME }}
          name: ${{ env.NAME }}
          commit: ${{ github.sha }}
